"use client"
import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AsideMenu } from "../components/asideMenu/AsideMenu";
import { AuthProvider } from "../context/AuthContext";
import { usePathname } from "next/navigation";
import { Header } from "@/src/components/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hiddenRoutes = [
    "/login",
    "/register",
    "/verify-email",
    "/complete-profile",
    "/password",
  ];

  const hideNavbar = hiddenRoutes.includes(pathname);
  return (
    <html lang="en" className={`${archivo.variable} h-full antialiased`}>
      <body style={{ backgroundColor: '#F7F8F9' }} className="h-screen flex flex-col overflow-hidden">
        {!hideNavbar && <div className="p-4"><Header /></div>}
        <div className="flex flex-1 overflow-hidden">
          {!hideNavbar && (
            <div className="p-4 flex h-full">
              <AsideMenu />
            </div>
          )}
          <main className="flex-1 overflow-y-auto p-4 pl-0">
            <div className="h-full w-full">
              <AuthProvider>{children}</AuthProvider>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
