import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AsideMenu } from "../components/asideMenu/AsideMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${archivo.variable} h-full antialiased`}>
      <body className="h-screen flex overflow-hidden">
        <div className="p-4 flex h-full">
          <AsideMenu />
        </div>
        <main className="flex-1 overflow-y-auto p-4 pl-0">
          <div className="h-full w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
